version: "3.8"
   
services:
  web:
    network_mode: "bridge"
    image: spandan13/whoishomeui:dev
    command: python /mysite/manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    ports:
     - 8032:80 # Change first value to any available port you wish to use
